name: testBuilding

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test npm run build
      run: |
        yarn
        yarn build
        yarn build:release
